name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # If your theme uses submodules
          fetch-depth: 0 # Needed for some Hugo features like GitInfo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Or a specific version like '0.120.4'
          extended: true # If using Hugo extended version

      - name: Build Hugo site
        run: hugo --minify # Add any other Hugo build arguments here, e.g., --buildFuture

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # Only deploy from the main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hugo's default output directory
          publish_branch: gh-pages # The branch where your built site will be pushed
